Add support for agent self-restarting on Linux
wazuh/wazuh-agent pull request #386
Opened 2024-12-04 14:19 UTC by lchico

|Related issue|
|---|
|https://github.com/wazuh/wazuh-agent/issues/77|

# Description
Base on the design phase, this PR implement how to handles the Wazuh agent restart process. Upon receiving a **restart command**, the program identifies the restart method (systemd or manual). It ensures the agent is stopped with a 30-second timeout, then restarts it. If the agent doesn’t stop gracefully, it is forcefully terminated. The process includes confirmation of the agent's successful restart.

<p align="center">
<img src="https://github.com/user-attachments/assets/37a905c5-ab58-48e2-b44d-2ae0d12a1337">
</p>

## Implementation Details:
- Once the command is received, the system will notify that the restart process is initializing before proceeding.
- Depending on how the agent was initially started, this module will use the same method for the restart, which could either be systemd or a manual method.
- If systemd was used, it will be responsible for stopping and restarting the agent, ensuring the process is killed if it hasn't restarted within 30 seconds. Any unexpected errors will be reported.
- For manual restarts, a fork is used to create a child process, which is responsible for stopping the current agent process, checking if it was closed before the timeout (also 30 seconds). If not, the agent will be killed and a new process will be started. Any unexpected errors will be reported.
- Once the agent has restarted, a success notification will be sent.

# Extra changes:

- The SIGTERM signal name was not recognized, so I replaced it with the corresponding value to avoid the following error:

```bash
# apt remove wazuh-agent
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following package was automatically installed and is no longer required:
  lsb-release
Use 'apt autoremove' to remove it.
The following packages will be REMOVED:
  wazuh-agent
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 15.5 MB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 9917 files and directories currently installed.)
Removing wazuh-agent (5.0.0-0) ...
Call pid 4119 with sigterm to stop the service
/var/lib/dpkg/info/wazuh-agent.prerm: 43: kill: Illegal option -S
dpkg: error processing package wazuh-agent (--remove):
 installed wazuh-agent package pre-removal script subprocess returned error exit status 2
dpkg: too many errors, stopping
Errors were encountered while processing:
 wazuh-agent
Processing was halted because there were too many errors.
E: Sub-process /usr/bin/dpkg returned an error code (1)	
```

- Fixed the following warning:

```bash
root@52347fca4dff:~/output# apt purge wazuh-agent
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following package was automatically installed and is no longer required:
  lsb-release
Use 'apt autoremove' to remove it.
The following packages will be REMOVED:
  wazuh-agent*
0 upgraded, 0 newly installed, 1 to remove and 11 not upgraded.
After this operation, 16.5 MB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 7766 files and directories currently installed.)
Removing wazuh-agent (5.0.0-0) ...
(Reading database ... 7759 files and directories currently installed.)
Purging configuration files for wazuh-agent (5.0.0-0) ...
dpkg: warning: while removing wazuh-agent, directory '/etc/wazuh-agent' not empty so not removed
root@52347fca4dff:~/output# ls /etc/wazuh-agent
shared
root@52347fca4dff:~/output#  ls /etc/wazuh-agent/shared/
validYaml.yml
```

# Test

### Server

```bash
wazuh-agent/src/tests/mock-server#   ./mock-server --http
```
Add the restart command action to `src/tests/mock-server/config/commands.groovy`

```bash
def actions = [
    ...
    ["name": "restart", "version": "v5.0.0"],
    ...
]
```

### Agent

Configure the agent to use the server address:

```bash
sed -i 's|server_url:.*|server_url: http://192.168.100.250:27000 |' /etc/wazuh-agent/wazuh-agent.yml
```

# Register the agent

```bash
# sudo SPDLOG_LEVEL=TRACE /usr/share/wazuh-agent/bin/wazuh-agent --user wazuh --password topsecret --url http://192.168.100.250:27000 --name dummy --register

vagrant@ubuntu2204:~$ sudo SPDLOG_LEVEL=TRACE /usr/share/wazuh-agent/bin/wazuh-agent --user wazuh --password topsecret --url http://192.168.100.250:27000 --name dummy --register
[2025-01-22 00:20:25.075] [wazuh-agent] [debug] [DEBUG] [configuration_parser.cpp:54] [LoadLocalConfig] Loading local config file: /etc/wazuh-agent/wazuh-agent.yml.
[2025-01-22 00:20:25.076] [wazuh-agent] [debug] [DEBUG] [configuration_parser.hpp:147] [GetConfig] Requested setting not found, default value used. Key not found: path.data
Starting wazuh-agent registration
[2025-01-22 00:20:25.217] [wazuh-agent] [debug] [DEBUG] [http_client.cpp:296] [PerformHttpRequest] Request /security/user/authenticate: Status 200
[2025-01-22 00:20:25.217] [wazuh-agent] [trace] [TRACE] [http_client.cpp:297] [PerformHttpRequest] Request endpoint: /security/user/authenticate
Response: HTTP/1.1 200 OK
X-Imposter-Request: 6a273dcf-c7d0-4a47-86b6-0f049cb614d7
Server: imposter
content-length: 47

{ "data": { "token": "a1b2c3d4e5f6g7h8i9j0" } }
[2025-01-22 00:20:25.320] [wazuh-agent] [debug] [DEBUG] [http_client.cpp:296] [PerformHttpRequest] Request /agents: Status 201
[2025-01-22 00:20:25.320] [wazuh-agent] [trace] [TRACE] [http_client.cpp:297] [PerformHttpRequest] Request endpoint: /agents
Response: HTTP/1.1 201 Created
X-Imposter-Request: 9cdc2d69-3018-438b-b05a-bc89b36db9ff
Server: imposter
content-length: 0

wazuh-agent registered
```

# Manually run the agent
```
root@ubuntu2204:~$ sudo /usr/share/wazuh-agent/bin/wazuh-agent
...
[2025-01-22 03:27:33.168] [wazuh-agent] [info] [INFO] [agent.cpp:170] [operator()] Restart: Initiating self-restart
[2025-01-22 03:27:33.174] [wazuh-agent] [info] [INFO] [inventory.cpp:62] [Stop] Inventory module stopping...
[2025-01-22 03:27:33.182] [wazuh-agent] [info] [INFO] [command_handler.hpp:105] [CommandsProcessingTask] Done processing command: restart(restart)
[2025-01-22 03:27:33.519] [wazuh-agent] [info] [INFO] [logcollector.cpp:96] [Stop] Logcollector module stopped.
[2025-01-22 03:27:33.540] [wazuh-agent] [info] [INFO] [inventoryImp.cpp:1165] [Scan] Evaluation finished.
[2025-01-22 03:27:33.587] [wazuh-agent] [info] [INFO] [inventory.cpp:37] [Start] Inventory module stopped.
root@ubuntu2204:/home/vagrant# [2025-01-22 03:27:34.175] [wazuh-agent] [info] [INFO] [restart_unix.cpp:66] [StopAgent] Agent gracefully stopped.
[2025-01-22 03:27:34.175] [wazuh-agent] [info] [INFO] [restart_unix.cpp:94] [RestartWithFork] Starting wazuh agent in a new process.
[2025-01-22 03:27:34.180] [wazuh-agent] [info] [INFO] [process_options_unix.cpp:24] [StartAgent] Starting wazuh-agent
[2025-01-22 03:27:34.181] [wazuh-agent] [info] [INFO] [communicator.hpp:55] [Communicator] Using insecure connection.
[2025-01-22 03:27:34.188] [wazuh-agent] [info] [INFO] [communicator.cpp:28] [SendAuthenticationRequest] Successfully authenticated with the manager.
[2025-01-22 03:27:34.189] [wazuh-agent] [info] [INFO] [inventory.cpp:18] [Start] Inventory module started.
[2025-01-22 03:27:34.189] [wazuh-agent] [info] [INFO] [inventoryImp.cpp:1170] [SyncLoop] Module started.
[2025-01-22 03:27:34.189] [wazuh-agent] [info] [INFO] [inventoryImp.cpp:1153] [Scan] Starting evaluation.
[2025-01-22 03:27:34.190] [wazuh-agent] [info] [INFO] [logcollector.cpp:32] [Start] Logcollector module started.
[2025-01-22 03:27:34.191] [wazuh-agent] [info] [INFO] [file_reader.cpp:61] [AddLocalfiles] Reading log file: /var/log/auth.log
[2025-01-22 03:27:34.199] [wazuh-agent] [info] [INFO] [command_handler.hpp:146] [CleanUpInProgressCommands] Agent restarted successfully
```

# Using Systemd to run the agent

```bash
root@ubuntu2204:/home/vagrant# journalctl -xu wazuh-agent -f
...
Jan 22 16:31:18 ubuntu2204.localdomain env[10942]: [2025-01-22 16:3 [...]

2024-12-20 00:15 UTC, lchico commented on src/agent/CMakeLists.txt
> -    CentralizedConfiguration
It was duplicated, so I removed it.

2025-01-14 12:06 UTC, vikman90 requested changes
@lchico, in addition to these minor comments in the code, it would be necessary to review the initial design. This approach leaves two permanent processes:

```
systemd─┬─2*[agetty]
        └─init-systemd(Ub─┬─SessionLeader───Relay(889)───bash───wazuh-agent───wazuh-agent───7*[{wazuh-agent}]
```

IMO, one fundamental requirement is missing: that the agent lives in a single process and, when it receives the restart signal, then it forks, kills the parent process and relaunches wazuh-agent.

We will discuss whatever you need to define this design.
Also, I would ask you to leave details of this in the main comment of the PR.

Thanks.

2025-01-14 12:51 UTC, jr0me commented on src/agent/src/process_options_unix.cpp
> +            lockFileHandler.~LockFileHandler();
There is a `removeLockFile()` method if I'm not mistaken. Also, this is an object created on the stack, the destructor will be called when it goes out of scope, calling it manually could result in UB.

2025-01-14 13:42 UTC, lchico commented on src/agent/src/process_options_unix.cpp
> +            lockFileHandler.~LockFileHandler();
The removeLockFile() method is now private. I need a hard remove because the SIGKILL signal will shut down the service abruptly, preventing a graceful removal of the lock file. But yes, I need to find a better solution for this.

2025-01-14 14:01 UTC, jr0me commented on src/agent/src/process_options_unix.cpp
> +            lockFileHandler.~LockFileHandler();
Would probably be better to just make the method public.

2025-01-23 10:25 UTC, sdvendramini commented on src/agent/command_handler/include/command_handler.hpp
> +                        cmd.value().ExecutionResult.ErrorCode = module_command::Status::IN_PROGRESS;
I think at this point, the cmd is already in `IN_PROGRESS` status. It's created with this status when it is extracted from the queue.

2025-01-23 13:48 UTC, sdvendramini commented on src/agent/restart/src/restart_unix.cpp
> +        if (std::system("systemctl restart wazuh-agent") != 0)
Can we try to avoid system calls? Maybe there is some library to restart the systemd services without using `std::system`?

2025-01-23 19:44 UTC, TomasTurina commented on src/agent/restart/src/restart_unix.hpp
> +    /// @param pid The process ID of the agent to stop.
Remove.

2025-01-23 19:44 UTC, TomasTurina commented on src/agent/restart/src/restart_unix.hpp
> +    bool UsingSystemctl();
Add return type to description.

2025-01-23 19:44 UTC, TomasTurina commented on src/agent/restart/src/restart_unix.hpp
> +    /// Returns a vector of null-terminated strings.
```suggestion
    ///
    /// @return A vector of null-terminated strings.
```

2025-01-23 19:55 UTC, TomasTurina commented on src/agent/restart/src/restart_unix.cpp
> +            co_return module_command::CommandExecutionResult {module_command::Status::IN_PROGRESS,
Is this code ever executed?

2025-01-23 19:56 UTC, TomasTurina commented on src/agent/restart/src/restart_unix.cpp
> +                kill(pid, SIGKILL);
```suggestion
                kill(pid, SIGKILL);
                break;
```
Just in case.

2025-01-23 20:00 UTC, TomasTurina commented on src/agent/src/agent.cpp
> +                else if (cmd.Module == "restart")
After rebase, add module name to [here](https://github.com/wazuh/wazuh-agent/blob/master/src/agent/command_handler/include/command_entry/command_entry.hpp#L17).

2025-01-23 20:01 UTC, TomasTurina commented on src/agent/command_handler/src/command_handler.cpp
> +            {"restart", {"restart", module_command::CommandExecutionMode::SYNC}}};
After rebase, add command name [here](https://github.com/wazuh/wazuh-agent/blob/master/src/agent/command_handler/include/command_entry/command_entry.hpp#L10). (also module name)

2025-01-23 20:04 UTC, TomasTurina commented on src/agent/command_handler/include/command_handler.hpp
> +                    if (cmd.value().Module == "restart")
Is this block if necessary? This is already done as part of the dispatch command set in https://github.com/wazuh/wazuh-agent/pull/386/files#diff-da3d5e8dd4752020c509b5b337eb7254314aad465439e743138acdb52912a34cR171.

2025-01-23 20:06 UTC, TomasTurina commented on src/agent/command_handler/include/command_handler.hpp
> +                    if (cmd.Command == "restart")
After rebase, add command name [here](https://github.com/wazuh/wazuh-agent/blob/master/src/agent/command_handler/include/command_entry/command_entry.hpp#L10).

2025-01-23 20:07 UTC, TomasTurina reviewed
Please, check the comments.

2025-01-23 20:07 UTC, TomasTurina requested changes
Please, check the comments.

2025-01-24 01:48 UTC, lchico commented on src/agent/restart/src/restart_unix.cpp
> +                kill(pid, SIGKILL);
Yes, I wasn't sure whether to take the break or leave it for the next interaction, just to be sure that the process was over.

2025-01-24 01:55 UTC, lchico commented on src/agent/restart/src/restart_unix.cpp
> +        if (std::system("systemctl restart wazuh-agent") != 0)
I did some research, and it doesn't seem straightforward to avoid system calls for restarting systemd services. For now, I would prefer to leave it as is. We could consider improving it in the future. What do you think?

2025-01-24 01:55 UTC, lchico commented on src/agent/command_handler/src/command_handler.cpp
> +            {"restart", {"restart", module_command::CommandExecutionMode::SYNC}}};
Done. Thanks for the feedback and the pointer!

2025-01-24 02:00 UTC, lchico commented on src/agent/command_handler/include/command_handler.hpp
> +                    if (cmd.Command == "restart")
Done. Thanks for the feedback and the pointer!

2025-01-24 13:20 UTC, jr0me commented on src/agent/restart/CMakeLists.txt
> +project(Restart)
Can we rename the project to something a bit more descriptive? `RestartHandler` or `RestartCommandHandler` are ones that come to mind. "Restart" by itself is a very common word and could difficult lookup, beyond the fact that it doesn't tell the full story of the class responsibilities.

2025-01-24 13:22 UTC, TomasTurina commented
Please, add command description to `docs/ref/commands.md`.

2025-01-24 13:51 UTC, jr0me commented on src/agent/restart/CMakeLists.txt
> +target_link_libraries(Restart PUBLIC Boost::asio nlohmann_json::nlohmann_json CommandEntry PRIVATE Logger)
It doesn't look like nlohmann_json is being used.

2025-01-24 13:51 UTC, jr0me commented on src/agent/restart/include/restart.hpp
> +#include <vector>
Not needed here

2025-01-24 13:51 UTC, jr0me commented on src/agent/restart/src/restart_unix.hpp
> +    std::vector<char*> GetCommandLineArgs();
Can we use `std::vector<std::string>` instead?

2025-01-24 13:51 UTC, jr0me commented on src/agent/restart/src/restart_unix.cpp
> +            std::this_thread::sleep_for(std::chrono::seconds(1));
Missing includes for `thread` and `chrono` for this line.

2025-01-24 13:51 UTC, jr0me commented on src/agent/restart/src/restart_unix.cpp
> +
Maybe this can be improved by using a vector of strings, otherwise we are creating a string, then converting it to c_str() and finally adding a nullptr to the vector.

2025-01-24 13:51 UTC, jr0me commented on src/agent/restart/src/restart_unix.cpp
> +        std::ifstream cmdline_file("/proc/self/cmdline");
How could this fail? Do all linux platforms support this? (including osx) Maybe we can save the arguments when the agent starts?

2025-01-24 18:05 UTC, TomasTurina commented on src/agent/restart/src/restart_unix.cpp
> +                kill(pid, SIGKILL);
I agree.

2025-01-24 18:06 UTC, TomasTurina commented on src/agent/restart/CMakeLists.txt
> +project(Restart)
I go with `RestartHandler`.

2025-01-24 22:29 UTC, lchico commented on src/agent/restart/src/restart_unix.cpp
> +        std::ifstream cmdline_file("/proc/self/cmdline");
That's a great idea! Thank you!

2025-01-25 00:09 UTC, lchico commented on src/agent/restart/src/restart_unix.hpp
> +    std::vector<char*> GetCommandLineArgs();
Yes, I can use `std::vector<std::string>`, but I need to convert the strings to `char*` in order to use them with `execve`.

2025-01-27 13:00 UTC, jr0me commented on src/agent/restart/src/restart_unix.cpp
> +
No worries, the multiple castings from char* to strings is no longer there and it's looking much better, thanks!

2025-01-27 14:38 UTC, TomasTurina commented on src/agent/command_handler/include/command_entry/command_entry.hpp
> +    const std::string RESTART_MODULE = "Restart";
```suggestion
    const std::string RESTART_HANDLER_MODULE = "RestartHandler";
```

2025-01-27 14:53 UTC, TomasTurina commented on src/agent/restart_handler/src/restart_handler_win.cpp
> +        // TODO
Is there an open issue to implement this?

2025-01-27 14:58 UTC, TomasTurina commented on src/agent/restart_handler/src/restart_handler_unix.cpp
> +                LogError("Failed to spawn new Wazuh agent process.");
What if this happens, how the restart result is notified?

2025-01-27 14:59 UTC, TomasTurina commented on src/agent/restart_handler/src/restart_handler_unix.cpp
> +        if (UsingSystemctl())
Shouldn't you do something similar in macOS? Have you tested in macOS?

2025-01-27 15:29 UTC, lchico commented on src/agent/restart_handler/src/restart_handler_win.cpp
> +        // TODO
Not yet. Do you think I should create it?

2025-01-27 15:31 UTC, lchico commented on src/agent/restart_handler/src/restart_handler_unix.cpp
> +        if (UsingSystemctl())
We should probably do that, but we could address it in another issue. I haven't tested it on macOS.

2025-01-27 16:02 UTC, lchico commented on src/agent/restart_handler/src/restart_handler_unix.cpp
> +                LogError("Failed to spawn new Wazuh agent process.");
In this case, it won't be possible since the agent is already stopped. What I can do is try to execute it three more times, maybe. What do you think?

2025-01-27 16:06 UTC, TomasTurina commented on src/agent/restart_handler/src/restart_handler_unix.cpp
> +        if (UsingSystemctl())
In that case, why don't you create a `restart_handler_lin.cpp` and `restart_handler_mac.cpp` (similar to win)?

2025-01-27 16:07 UTC, TomasTurina commented on src/agent/restart_handler/src/restart_handler_win.cpp
> +        // TODO
Yes, let's open one for Windows and one for macOS.

2025-01-27 16:15 UTC, lchico commented on src/agent/restart_handler/src/restart_handler_unix.cpp
> +        if (UsingSystemctl())
> Shouldn't you do something similar in macOS (launchctl command)? Have you tested in macOS?
I think it's very likely that it will work for Linux and macOS. 
As you mentioned, we should add a conditional for launchctl, so we don't need another file. 

> In that case, why don't you create a restart_handler_lin.cpp and restart_handler_mac.cpp (similar to win)?
I believe this could be addressed in the macOS issue if needed.

2025-01-27 16:29 UTC, TomasTurina commented on src/agent/restart_handler/src/restart_handler_unix.cpp
> +        if (UsingSystemctl())
Ok, so please upload a test of this working on macOS to complete evidence.

2025-01-28 02:11 UTC, jr0me approved these changes
I left a few comments, mostly on formatting and style, but already LGTM

2025-01-28 02:11 UTC, jr0me commented on src/agent/restart_handler/CMakeLists.txt
> +
Extra line, can be removed.

2025-01-28 02:11 UTC, jr0me commented on src/agent/restart_handler/CMakeLists.txt
> +# endif()
We could remove this.

2025-01-28 02:11 UTC, jr0me commented on src/agent/restart_handler/include/restart_handler.hpp
> +#pragma once
Can we insert a line after `#pragma once`?

2025-01-28 02:11 UTC, jr0me commented on src/agent/restart_handler/include/restart_handler.hpp
> +            RestartHandler::cmd_line.emplace_back(nullptr);
This is the type of line that could warrant some comment as it may not be obvious at first inspection why it is needed.

2025-01-28 02:11 UTC, jr0me commented on src/agent/restart_handler/src/restart_handler_unix.cpp
> +        time_t start_time = time(nullptr); // Record the start time to track the timeout duration
Could be better to say `timeoutSeconds`, `timeoutInSecs`, etc... `startTime` doesn't need a comment, and could be const.

2025-01-28 02:43 UTC, lchico commented on src/agent/restart_handler/src/restart_handler_unix.cpp
> +        if (UsingSystemctl())
Sure, I tested it [here](https://github.com/wazuh/wazuh-agent/actions/runs/12990813666/job/36226889350?pr=547#:~:text=35/39%20Test,1658).

2025-01-28 02:45 UTC, lchico commented on src/agent/restart_handler/src/restart_handler_win.cpp
> +        // TODO
* [Add support for agent self-restarting for Windows #552](https://github.com/wazuh/wazuh-agent/issues/552)
* [Add support for agent self-restarting for macOS #553](https://github.com/wazuh/wazuh-agent/issues/553)

2025-01-28 15:58 UTC, TomasTurina approved these changes

2025-01-28 16:04 UTC, MarcelKemp approved these changes

2025-01-28 16:17 UTC, vikman90 approved these changes
Now, we've got just one process:

```
SessionLeader───Relay(130993)───bash───wazuh-agent───6*[{wazuh-agent}]
```

Thanks @lchico!

2025-01-28 17:30 UTC, merged