Fix ensure file vault is enabled for mac os 13 14
wazuh/wazuh-agent pull request #74
Opened 2024-08-10 08:38 UTC by l-with

|Related issue|
|---|
| #73  |

## Description

## Configuration options

## Logs/Alerts example

## Tests

- Compilation without warnings in every supported platform
  - [ ] Linux
  - [ ] Windows
  - [x] MAC OS X
- [ ] Source installation
- [x] Package installation
- [ ] Source upgrade
- [ ] Package upgrade
- [ ] Review logs syntax and correct language
- [ ] QA templates contemplate the added capabilities

- Memory tests for Linux
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Valgrind (memcheck and descriptor leaks check)
  - [ ] Dr. Memory
  - [ ] AddressSanitizer
- Memory tests for Windows
  - [ ] Scan-build report
  - [ ] Coverity
  - [ ] Dr. Memory
- Memory tests for macOS
  - [ ] Scan-build report
  - [ ] Leaks
  - [ ] AddressSanitizer

- [ ] Retrocompatibility with older Wazuh versions
- [ ] Working on cluster environments
- [ ] Configuration on demand reports new parameters
- [ ] The data flow works as expected (agent-manager-api-app)
- [ ] Added unit tests (for new features)
- [ ] Stress test for affected components

- Decoder/Rule tests
  - [ ] Added unit testing files ".ini"
  - [ ] runtests.py executed without errors

2024-08-21 04:59 UTC, l-with commented
This is simple bug and fix, is there anybody out there to review?

2024-08-29 16:19 UTC, TomasTurina approved these changes

2024-08-29 16:20 UTC, TomasTurina requested changes
@l-with Please sign your commits so we can merge this change.

2024-08-31 16:22 UTC, l-with commented
> @l-with Please sign your commits so we can merge this change.

done

2024-09-03 14:34 UTC, TomasTurina approved these changes

2024-09-03 14:34 UTC, merged